# Generated by Django 3.2.7 on 2021-09-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Consult',
        ),
    ]
