# Generated by Django 3.2.7 on 2021-09-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultAPI', '0002_rename_user_consult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_saude', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('tratamnento_medico', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('medicamento', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('alergia_medicamento', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('fumante', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('sangramento_gengiva', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('sensibilidade', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('roi_unhas', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('morder_caneta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('fio_dental', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], default='N', max_length=3)),
                ('outro_habito', models.TextField(max_length=300)),
                ('higiene', models.CharField(choices=[('B', 'Boa'), ('R', 'Regular'), ('r', 'Ruim')], default='B', max_length=1)),
                ('halitose', models.CharField(choices=[('A', 'Ausente'), ('P', 'Presente')], default='P', max_length=1)),
                ('mucosa', models.CharField(choices=[('A', 'Ausente'), ('P', 'Presente')], default='P', max_length=1)),
                ('lingua', models.CharField(max_length=100)),
                ('palato', models.CharField(max_length=100)),
                ('palato_mole', models.CharField(max_length=100)),
                ('assoalho_bucal', models.CharField(max_length=100)),
                ('labios', models.CharField(max_length=100)),
                ('placa_bacteriana_invisivel', models.CharField(choices=[('A', 'Ausente'), ('P', 'Presente')], default='P', max_length=1)),
                ('sangramento_gengival', models.CharField(choices=[('A', 'Ausente'), ('P', 'Presente')], default='P', max_length=1)),
                ('tartaro', models.CharField(choices=[('A', 'Ausente'), ('P', 'Presente')], default='P', max_length=1)),
                ('mobilidade_dental', models.CharField(choices=[('A', 'Ausente'), ('P', 'Presente')], default='P', max_length=1)),
                ('apinhamento', models.CharField(choices=[('A', 'Ausente'), ('L', 'Leve'), ('S', 'Severo')], default='A', max_length=1)),
                ('diastemas', models.CharField(choices=[('A', 'Ausente'), ('P', 'Presente')], default='P', max_length=1)),
                ('observacoes', models.TextField(blank=True)),
                ('tratamento', models.TextField(blank=True)),
            ],
        ),
    ]
